baseURL = 'https://melonvin.github.io/'
languageCode = 'en-us'
title = 'JavaScript World of Melonvin'

Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

# this setting should always be set to false, otherwise it will break the section navigation bar
pluralizelisttitles = false

[params]
  author = "Melonvin"
  description = "Minimal, one page, theme for showcasing your work"
  message = ""
  hideAutoMenu = false
  
  # Pagination options
  paginate = 3
  multipage = true

  # Dark mode
  darkMode = true

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/Melonvin"

[social]
  facebook = "https://facebook.com"
  twitter = "https://twitter.com"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"